//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeWell.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeWell.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not authorized to use the service. The error is {0}.
        /// </summary>
        internal static string HttpClient401Error {
            get {
                return ResourceManager.GetString("HttpClient401Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while deserializing the received data.
        /// </summary>
        internal static string HttpClientGetDataDeserializeErrorText {
            get {
                return ResourceManager.GetString("HttpClientGetDataDeserializeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception while getting data.
        /// </summary>
        internal static string HttpClientGetDataUnknownErrorText {
            get {
                return ResourceManager.GetString("HttpClientGetDataUnknownErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException while getting data.
        /// </summary>
        internal static string HttpClientGetDataWebErrorText {
            get {
                return ResourceManager.GetString("HttpClientGetDataWebErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method doesn&apos;t support HttpGet operations. Use the get method instead.
        /// </summary>
        internal static string HttpClientGetInPostMethodError {
            get {
                return ResourceManager.GetString("HttpClientGetInPostMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected key {0} is null or empty so the Uri segement cannot be formed.
        /// </summary>
        internal static string HttpClientNullParamKey {
            get {
                return ResourceManager.GetString("HttpClientNullParamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected value {0} is null or empty so the Uri segement cannot be formed.
        /// </summary>
        internal static string HttpClientNullParamValue {
            get {
                return ResourceManager.GetString("HttpClientNullParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception while sending data.
        /// </summary>
        internal static string HttpClientSendDataUnknownErrorText {
            get {
                return ResourceManager.GetString("HttpClientSendDataUnknownErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException while sending data.
        /// </summary>
        internal static string HttpClientSendDataWebErrorText {
            get {
                return ResourceManager.GetString("HttpClientSendDataWebErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while getting data from url {0}. The error is {1}.
        /// </summary>
        internal static string HttpClientUnknownError {
            get {
                return ResourceManager.GetString("HttpClientUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting tours. The error is {0}.
        /// </summary>
        internal static string ManagementServiceProxyAddTours {
            get {
                return ResourceManager.GetString("ManagementServiceProxyAddTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding tours. The error is {0}.
        /// </summary>
        internal static string ManagementServiceProxyDeleteTours {
            get {
                return ResourceManager.GetString("ManagementServiceProxyDeleteTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required parameter {0} was missing.
        /// </summary>
        internal static string ParamNullMessage {
            get {
                return ResourceManager.GetString("ParamNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while checking in user. The error is {0}.
        /// </summary>
        internal static string ServiceProxyCheckInError {
            get {
                return ResourceManager.GetString("ServiceProxyCheckInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the user. The error is {0}.
        /// </summary>
        internal static string ServiceProxyDeleteUserError {
            get {
                return ResourceManager.GetString("ServiceProxyDeleteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get location. The error is {0}.
        /// </summary>
        internal static string ServiceProxyGetLocationError {
            get {
                return ResourceManager.GetString("ServiceProxyGetLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting tours. The error is {0}.
        /// </summary>
        internal static string ServiceProxyGetTours {
            get {
                return ResourceManager.GetString("ServiceProxyGetTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid.
        /// </summary>
        internal static string ServiceProxyInvalidToken {
            get {
                return ResourceManager.GetString("ServiceProxyInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while getting the users token. The error is {0}.
        /// </summary>
        internal static string ServiceProxyUnknownAuthError {
            get {
                return ResourceManager.GetString("ServiceProxyUnknownAuthError", resourceCulture);
            }
        }
    }
}
